app:
  jwt:
    secret: YOUR_VERY_LONG_SECRET_KEY_THAT_IS_AT_LEAST_32_CHARACTERS_LONG
    expirationMs: 86400000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minilmsdb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: MicroLMS
  mail:
    host: smtp.gmail.com
    port: 587
    username: jaffarbangash787@gmail.com
    password: kszjgbwvyekotrrr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true